#!/bin/bash

echo "################# $SOURCE_BRANCH"

version="latest"

if [ $SOURCE_BRANCH != "master" ] ; then
    version=$SOURCE_BRANCH
fi

DOCKER_TAG=$(echo ${version} | sed 's/\(.*\)\/\(.*\)/\1_\2/')
tag=${DOCKER_REPO}:${DOCKER_TAG}
echo "########################## $tag"
docker push $tag
